# Generated by Django 4.0.4 on 2022-05-05 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 16, 14, 26, 529643)),
        ),
    ]
